Fix S3 connection error
This fixes the error

    CertificateError: hostname ‘ourcompany.images.s3.amazonaws.com’ doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'

I don’t expect this to be merged, but I thought people wanting to update their old S3/CloudFront sites might want to know, especially now that SSL is available for free. :)